name = "imemos"
main = "src/index.js"
compatibility_date = "2024-02-20"
compatibility_flags = ["nodejs_compat"]

[vars]
SITE_NAME = "归零杂记"
NAV_LINKS = "{'博客':'https://www.dengchangdong.com','热点':'https://news.dengchangdong.com'}"
PAGE_LIMIT = "10"
API_HOST = "https://open.memos.dengchangdong.com"

[observability.logs]
enabled = false

[triggers]
crons = []
