name = "memos-themes"
main = "src/index.js"
compatibility_date = "2024-02-20"

[vars]
API_HOST = "https://open.memos.dengchangdong.com"
PAGE_LIMIT = "10"
SITE_NAME = "我的 Memos"
NAV_LINKS = "首页:/,关于:/about,归档:/archive"
FOOTER_TEXT = "© 2024 我的 Memos. All rights reserved."

[site]
bucket = "./public" 